#pragma once
#define AUTOCUT_PRODUCT_VERSION "1.2.0"
#define AUTOCUT_PRODUCT_VERSION_MAJOR 1
#define AUTOCUT_PRODUCT_VERSION_MINOR 2
#define AUTOCUT_PRODUCT_VERSION_PATCH 0
#define AUTOCUT_EFFECT_VERSION 589824
#define AUTOCUT_COLOR_MATCH_NAME "com.autocutstudio.color.engine"
