#pragma once
#define AUTOCUT_PRODUCT_VERSION "1.1.1"
#define AUTOCUT_PRODUCT_VERSION_MAJOR 1
#define AUTOCUT_PRODUCT_VERSION_MINOR 1
#define AUTOCUT_PRODUCT_VERSION_PATCH 1
#define AUTOCUT_EFFECT_VERSION 559104
#define AUTOCUT_COLOR_MATCH_NAME "com.autocutstudio.color.engine"
