use std::collections::HashSet;
use std::env;
use std::error::Error;
use std::ffi::OsString;
use std::fmt::Write as _;
use std::fs;
use std::io;
use std::path::{Component, Path, PathBuf};
use std::process::Command;

type BuildResult<T> = Result<T, Box<dyn Error>>;

const MAX_DIRECTORY_DEPTH: usize = 64;
const MAX_PAYLOAD_FILES: usize = 100_000;
const MAX_PAYLOAD_BYTES: u64 = 2 * 1024 * 1024 * 1024;

struct PayloadFile {
    relative_path: String,
    absolute_path: PathBuf,
}

fn main() {
    if let Err(error) = build() {
        // Cargo reports build-script failure and preserves this diagnostic.
        eprintln!("AutoCutStudio installer build failed: {error}");
        std::process::exit(1);
    }
}

fn build() -> BuildResult<()> {
    for variable in [
        "AUTOCUT_PACKAGE_DIR",
        "AUTOCUT_RC",
        "CARGO_FEATURE_EMBEDDED_PAYLOAD",
        "PATH",
        "WindowsSdkDir",
        "WindowsSDKVersion",
        "ProgramFiles(x86)",
        "ProgramFiles",
        "HOST",
        "TARGET",
    ] {
        println!("cargo:rerun-if-env-changed={variable}");
    }

    watch_path(Path::new("build.rs"))?;

    let manifest_dir = fs::canonicalize(required_env_path("CARGO_MANIFEST_DIR")?)?;
    let out_dir = required_env_path("OUT_DIR")?;
    fs::create_dir_all(&out_dir)?;
    let out_dir = fs::canonicalize(out_dir)?;
    let generated_path = out_dir.join("generated_files.rs");

    let embedded = env::var_os("CARGO_FEATURE_EMBEDDED_PAYLOAD").is_some();

    if !embedded {
        write_if_changed(
            &generated_path,
            b"// Generated by build.rs. Do not edit.\n\
              const FILES: &[FileEntry] = &[];\n",
        )?;
        return Ok(());
    }

    let package_dir = package_directory(&manifest_dir)?;
    watch_path(&package_dir)?;

    if !package_dir.is_dir() {
        return Err(format!(
            "extension package directory is missing: {}. \
             Set AUTOCUT_PACKAGE_DIR or build the extension package first.",
            package_dir.display()
        )
        .into());
    }

    // Resolve the root once. Symlinks inside the payload are rejected below.
    let package_dir = fs::canonicalize(package_dir)?;

    if out_dir.starts_with(&package_dir) || manifest_dir.starts_with(&package_dir) {
        return Err("the payload directory must not contain the installer crate or OUT_DIR".into());
    }

    let mut files = Vec::new();
    let mut destinations = HashSet::new();
    let mut total_bytes = 0;

    collect_files(
        &package_dir,
        &package_dir,
        0,
        &mut files,
        &mut destinations,
        &mut total_bytes,
    )?;

    if files.is_empty() {
        return Err("the extension package contains no files to embed".into());
    }

    // Stable ordering makes generated source independent of directory iteration.
    files.sort_by(|left, right| left.relative_path.cmp(&right.relative_path));

    let mut generated = String::from(
        "// Generated by build.rs. Do not edit.\n\
         const FILES: &[FileEntry] = &[\n",
    );

    for file in &files {
        let include_path = utf8_path(&file.absolute_path)?;

        /*
         * Debug formatting of str emits escaped Rust string literals.
         * Unlike ad-hoc raw strings, this safely handles quotes, backslashes,
         * and strings containing raw-string delimiters.
         */
        writeln!(
            generated,
            "    FileEntry {{ relative_path: {:?}, bytes: include_bytes!({:?}) }},",
            file.relative_path, include_path,
        )?;
    }

    generated.push_str("];\n");
    write_if_changed(&generated_path, generated.as_bytes())?;

    let target_os = env::var("CARGO_CFG_TARGET_OS").unwrap_or_default();

    if target_os == "windows" {
        let target_env = env::var("CARGO_CFG_TARGET_ENV").unwrap_or_default();

        /*
         * This path produces a Windows .res file for an MSVC-compatible linker.
         * GNU Windows targets require a separate windres/COFF integration.
         * Fail explicitly instead of silently omitting the UAC manifest.
         */
        if target_env != "msvc" {
            return Err(
                "embedded Windows installer builds currently require an MSVC target; \
                 GNU Windows targets need a windres/COFF resource pipeline"
                    .into(),
            );
        }

        compile_manifest(&manifest_dir, &out_dir)?;
    }

    Ok(())
}

fn required_env_path(name: &str) -> BuildResult<PathBuf> {
    let value = env::var_os(name)
        .filter(|value| !value.is_empty())
        .ok_or_else(|| format!("required environment variable {name} is missing or empty"))?;

    Ok(PathBuf::from(value))
}

fn package_directory(manifest_dir: &Path) -> BuildResult<PathBuf> {
    match env::var_os("AUTOCUT_PACKAGE_DIR") {
        Some(value) if value.is_empty() => Err("AUTOCUT_PACKAGE_DIR must not be empty".into()),
        Some(value) => {
            let path = PathBuf::from(value);

            // Relative overrides have an explicit, stable base.
            Ok(if path.is_absolute() {
                path
            } else {
                manifest_dir.join(path)
            })
        }
        None => {
            let workspace = manifest_dir
                .parent()
                .and_then(Path::parent)
                .ok_or("cannot infer package location; set AUTOCUT_PACKAGE_DIR explicitly")?;

            Ok(workspace.join("dist").join("com.autocutstudio.panel"))
        }
    }
}

fn utf8_path(path: &Path) -> BuildResult<&str> {
    path.to_str().ok_or_else(|| {
        format!(
            "a build path is not valid UTF-8 and cannot be embedded in Rust source: {:?}",
            path
        )
        .into()
    })
}

fn watch_path(path: &Path) -> BuildResult<()> {
    let text = utf8_path(path)?;

    // Cargo build-script directives are line-oriented.
    if text.contains(['\r', '\n']) {
        return Err(format!("build paths must not contain line breaks: {path:?}").into());
    }

    println!("cargo:rerun-if-changed={text}");
    Ok(())
}

fn collect_files(
    root: &Path,
    directory: &Path,
    depth: usize,
    files: &mut Vec<PayloadFile>,
    destinations: &mut HashSet<String>,
    total_bytes: &mut u64,
) -> BuildResult<()> {
    if depth > MAX_DIRECTORY_DEPTH {
        return Err(format!(
            "payload directory nesting exceeds {MAX_DIRECTORY_DEPTH} levels: {}",
            directory.display()
        )
        .into());
    }

    // Watching directories also detects added and removed files.
    watch_path(directory)?;

    let mut entries = fs::read_dir(directory)?.collect::<Result<Vec<_>, io::Error>>()?;
    entries.sort_by_key(|entry| entry.file_name());

    for entry in entries {
        let path = entry.path();
        let metadata = fs::symlink_metadata(&path)?;

        if metadata.file_type().is_symlink() {
            return Err(format!(
                "symbolic links are not permitted inside the installer payload: {}",
                path.display()
            )
            .into());
        }

        reject_windows_reparse_point(&metadata, &path)?;

        if entry.file_name() == ".gitkeep" && metadata.is_file() {
            continue;
        }

        let relative = path.strip_prefix(root)?;
        let relative_path = validated_relative_path(relative)?;

        /*
         * Windows destinations are ordinarily case-insensitive. Reject
         * collisions before generating an archive that overwrites itself.
         * Unicode case folding here is conservative, not a complete model of
         * every filesystem's name-comparison rules.
         */
        let destination_key = relative_path.to_lowercase();

        if !destinations.insert(destination_key) {
            return Err(format!(
                "duplicate or case-colliding payload destination: {relative_path}"
            )
            .into());
        }

        if metadata.is_dir() {
            collect_files(root, &path, depth + 1, files, destinations, total_bytes)?;
        } else if metadata.is_file() {
            if files.len() >= MAX_PAYLOAD_FILES {
                return Err(
                    format!("payload exceeds the maximum of {MAX_PAYLOAD_FILES} files").into(),
                );
            }

            *total_bytes = total_bytes
                .checked_add(metadata.len())
                .ok_or("payload size overflow")?;

            if *total_bytes > MAX_PAYLOAD_BYTES {
                return Err(format!(
                    "payload exceeds the {MAX_PAYLOAD_BYTES}-byte embedding limit"
                )
                .into());
            }

            watch_path(&path)?;

            files.push(PayloadFile {
                relative_path,
                absolute_path: path,
            });
        } else {
            return Err(format!(
                "unsupported filesystem entry inside payload: {}",
                path.display()
            )
            .into());
        }
    }

    Ok(())
}

#[cfg(windows)]
fn reject_windows_reparse_point(metadata: &fs::Metadata, path: &Path) -> BuildResult<()> {
    use std::os::windows::fs::MetadataExt;

    const FILE_ATTRIBUTE_REPARSE_POINT: u32 = 0x0400;

    if metadata.file_attributes() & FILE_ATTRIBUTE_REPARSE_POINT != 0 {
        return Err(format!(
            "Windows reparse points are not permitted inside the payload: {}",
            path.display()
        )
        .into());
    }

    Ok(())
}

#[cfg(not(windows))]
fn reject_windows_reparse_point(_: &fs::Metadata, _: &Path) -> BuildResult<()> {
    Ok(())
}

fn validated_relative_path(path: &Path) -> BuildResult<String> {
    let mut parts = Vec::new();

    for component in path.components() {
        let Component::Normal(name) = component else {
            return Err(format!("unsafe relative payload path: {path:?}").into());
        };

        let name = name
            .to_str()
            .ok_or_else(|| format!("payload filename is not valid UTF-8: {path:?}"))?;

        if name.is_empty()
            || name.ends_with(['.', ' '])
            || name.chars().any(|character| {
                character.is_control()
                    || matches!(
                        character,
                        '<' | '>' | ':' | '"' | '/' | '\\' | '|' | '?' | '*'
                    )
            })
        {
            return Err(format!("filename is not portable to Windows: {path:?}").into());
        }

        let stem = name
            .split('.')
            .next()
            .unwrap_or("")
            .trim_end_matches(' ')
            .to_uppercase();

        let numbered_device = stem
            .strip_prefix("COM")
            .or_else(|| stem.strip_prefix("LPT"))
            .map(|suffix| {
                matches!(
                    suffix,
                    "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" | "¹" | "²" | "³"
                )
            })
            .unwrap_or(false);

        if matches!(
            stem.as_str(),
            "CON" | "PRN" | "AUX" | "NUL" | "CLOCK$" | "CONIN$" | "CONOUT$"
        ) || numbered_device
        {
            return Err(format!("reserved Windows filename in payload: {path:?}").into());
        }

        parts.push(name);
    }

    if parts.is_empty() {
        return Err("payload destination path must not be empty".into());
    }

    Ok(parts.join("/"))
}

fn compile_manifest(manifest_dir: &Path, out_dir: &Path) -> BuildResult<()> {
    let source_dir = manifest_dir.join("src");
    let resource_script = source_dir.join("manifest.rc");
    let resource_output = out_dir.join("manifest.res");

    if !resource_script.is_file() {
        return Err(format!(
            "UAC resource script is missing: {}",
            resource_script.display()
        )
        .into());
    }

    /*
     * Watch local manifest/resource dependencies, not only manifest.rc.
     * Resources included from outside src need their own rerun-if-changed
     * directives in this build script.
     */
    watch_path(&source_dir)?;

    let compiler = find_resource_compiler()?;
    watch_path(&compiler)?;

    // A failed compiler invocation must not leave a stale resource to link.
    match fs::remove_file(&resource_output) {
        Ok(()) => {}
        Err(error) if error.kind() == io::ErrorKind::NotFound => {}
        Err(error) => return Err(error.into()),
    }

    let output = Command::new(&compiler)
        .current_dir(&source_dir)
        .arg("/nologo")
        .arg("/I")
        .arg(&source_dir)
        .arg("/fo")
        .arg(&resource_output)
        .arg(&resource_script)
        .output()
        .map_err(|error| {
            format!(
                "could not execute resource compiler {}: {error}",
                compiler.display()
            )
        })?;

    if !output.status.success() {
        return Err(format!(
            "resource compiler {} failed with {}:\n{}\n{}",
            compiler.display(),
            output.status,
            String::from_utf8_lossy(&output.stdout),
            String::from_utf8_lossy(&output.stderr)
        )
        .into());
    }

    if !resource_output.is_file() || fs::metadata(&resource_output)?.len() == 0 {
        return Err("resource compiler succeeded but produced no manifest resource".into());
    }

    let resource_path = utf8_path(&resource_output)?;

    if resource_path.contains(['\r', '\n']) {
        return Err("resource output path contains a line break".into());
    }

    // Resource embedding is needed for installer binaries, not test targets.
    println!("cargo:rustc-link-arg-bins={resource_path}");
    Ok(())
}

fn find_resource_compiler() -> BuildResult<PathBuf> {
    if let Some(override_path) = env::var_os("AUTOCUT_RC") {
        if override_path.is_empty() {
            return Err("AUTOCUT_RC must not be empty".into());
        }

        if let Some(path) = resolve_executable(&override_path) {
            return Ok(path);
        }

        return Err(format!(
            "AUTOCUT_RC does not identify an existing compiler executable: {:?}",
            override_path
        )
        .into());
    }

    // Search tools runnable on the build host, not the compilation target.
    let names: &[&str] = if cfg!(windows) {
        &["rc.exe", "llvm-rc.exe"]
    } else {
        &["llvm-rc"]
    };

    for name in names {
        if let Some(path) = resolve_executable(&OsString::from(name)) {
            return Ok(path);
        }
    }

    if cfg!(windows) {
        let mut roots = Vec::new();

        if let Some(root) = env::var_os("WindowsSdkDir") {
            roots.push(PathBuf::from(root).join("bin"));
        }

        for variable in ["ProgramFiles(x86)", "ProgramFiles"] {
            if let Some(root) = env::var_os(variable) {
                roots.push(
                    PathBuf::from(root)
                        .join("Windows Kits")
                        .join("10")
                        .join("bin"),
                );
            }
        }

        for root in roots {
            if let Some(path) = find_sdk_resource_compiler(&root)? {
                return Ok(path);
            }
        }
    }

    Err(
        "a Windows resource compiler is required for the embedded installer. \
         Install the Windows SDK or LLVM, or set AUTOCUT_RC to an rc/llvm-rc executable. \
         The UAC manifest will not be silently omitted."
            .into(),
    )
}

fn resolve_executable(value: &OsString) -> Option<PathBuf> {
    let path = PathBuf::from(value);

    if path.is_absolute() || path.components().count() > 1 {
        return path
            .is_file()
            .then(|| fs::canonicalize(&path).ok())
            .flatten();
    }

    let search_path = env::var_os("PATH")?;

    for directory in env::split_paths(&search_path) {
        let candidate = directory.join(&path);

        if candidate.is_file() {
            if let Ok(absolute) = fs::canonicalize(candidate) {
                return Some(absolute);
            }
        }
    }

    None
}

fn find_sdk_resource_compiler(root: &Path) -> BuildResult<Option<PathBuf>> {
    if !root.is_dir() {
        return Ok(None);
    }

    let host = env::var("HOST").unwrap_or_default();

    let architectures: &[&str] = if host.starts_with("aarch64") {
        &["arm64", "x64", "x86"]
    } else if host.starts_with("x86_64") {
        &["x64", "x86"]
    } else {
        &["x86"]
    };

    let mut directories = Vec::new();

    if let Ok(version) = env::var("WindowsSDKVersion") {
        let version = version.trim_matches(['/', '\\']);

        if !version.is_empty() {
            directories.push(root.join(version));
        }
    }

    let mut versions = Vec::new();

    for entry in fs::read_dir(root)? {
        let entry = entry?;

        if !entry.file_type()?.is_dir() {
            continue;
        }

        let name = entry.file_name();

        if let Some(name) = name.to_str() {
            if let Some(version) = parse_sdk_version(name) {
                versions.push((version, entry.path()));
            }
        }
    }

    // Numeric comparison avoids lexicographic SDK-version ordering mistakes.
    versions.sort_by(|left, right| right.0.cmp(&left.0).then_with(|| left.1.cmp(&right.1)));

    directories.extend(versions.into_iter().map(|(_, path)| path));
    directories.push(root.to_path_buf());

    for directory in directories {
        for architecture in architectures {
            let candidate = directory.join(architecture).join("rc.exe");

            if candidate.is_file() {
                return Ok(Some(fs::canonicalize(candidate)?));
            }
        }
    }

    Ok(None)
}

fn parse_sdk_version(name: &str) -> Option<Vec<u32>> {
    if name.is_empty() {
        return None;
    }

    name.split('.')
        .map(|component| component.parse::<u32>().ok())
        .collect()
}

fn write_if_changed(path: &Path, contents: &[u8]) -> io::Result<()> {
    match fs::read(path) {
        Ok(existing) if existing == contents => return Ok(()),
        Ok(_) => {}
        Err(error) if error.kind() == io::ErrorKind::NotFound => {}
        Err(error) => return Err(error),
    }

    fs::write(path, contents)
}
